- scripts/build_podspec.sh
Motivation:
A number of users have asked for the ability to install
NIOTransportServices via Cocoapods. This is an entirely reasonable
request, so let's do it.
Modifications:
Added a script that can generate, and optionally upload, a specfile
for NIOTransportServices.
Result:
Users can use cocoapods if they prefer.
> Add Cocoapods podspec generation.

- README.md
Motivation:
Today, SwiftPM unfortunately doesn't offer a great story for macOS/iOS
App development. Therefore we should recommend the
SwiftNIO/SwiftNIOTransportServices Pods.
Modifications:
recommend CocoaPods in the readme
Result:
Hopefully less frustration.
> advertise CocoaPods over SwiftPM for NIOTS

- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
Use `DispatchWorkItem.cancel()` for cancellation. Make `ChannelState.beginActivating()` use the same methodology as all the others.
These things *irked* me. Especially the comment about Dispatch not providing for cancellation. Tsk, Tsk.
`NIOTSEventLoop.scheduleTask` will now create a cancellable `DispatchWorkItem` to be scheduled, and will use `workItem.cancel()` in the cancellation task for the returned `Scheduled` instance.
The state change methods in `ChannelState` for some reason contained two different methods of checking & handling the current state. I made them more uniform because reasons. *\*twitch\**
I will feel a lot happier.
> Some cleanliness changes.

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
Motivation:
In SwiftNIO 1.11 we'll ship improved interfaces for Channels to support
asserting being in the event loop. This is necessary because Dispatch
provides no non-precondition way to 100% guarantee that you are on a
specific queue, which is a requirement for accurate behaviour of
inEventLoop.
Right now this patch does not bring up the minimum required SwiftNIO version, so in some cases the old (more brittle) assertions will be used. We can raise the minimum required SwiftNIO version if we think it's worthwhile, but I suspect we don't actually need to do it: users who bump into this issue can just update SwiftNIO.
Modifications:
- Added an implementation of preconditionInEventLoop.
Result:
Accurate assertions
> Support preconditionInEventLoop.

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
Motivation:
If the user sets an unsupported ChannelOption we should give the best
diagnostics possible.
Modifications:
Add the ChannelOption type to the error message that it's unsupported.
Result:
Happier users
> better diagnostics if unsupported ChannelOption set

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
Motivation:
It is possible to receive the dataReceived callback after we've called
cancel, mostly because there may be such a block in place in the queue
before that cancel call fires. We should tolerate that.
Modifications:
Removed the invalid assertion.
Result:
Fewer failures.
> Remove invalid assertion.

- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
We were inadvertently modifying the registration information of
NIOTSEventLoop objects from multiple threads, which is very not good.
Modifications:
Add an event loop execute to hop loops.
Result:
Thread safe!
> Correctly hop across event loops during child channel setup.

- Sources/NIOTransportServices/StateManagedChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
In some cases, such as when an event loop has been shutdown, channel
registration may fail. In these cases, we would incorrectly attempt to
deregister the channel, which would fail (and in debug builds, assert).
Really, we shouldn't transition into .registered until we know that we have,
in fact, registered.
However, we need to be cautious: we don't want to register unless we
believe we're in an acceptable state to register.
Modifications:
Updated the state enum to perform the registration at the correct
part of the state change function.
Result:
Harder to crash in debug mode
> Don't transition to .registered unless registration succeeds.

- Package.swift
- README.md
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
SwiftPM from Swift 5.0 brings targets that only support certain systems
which is really handy for this package as it only support macOS 10.14+
and iOS/tvOS 12+
Modifications:
- made use of the Swift 5.0 manifests which can have restrictions on the
supported platforms
- adapted to NIO 2
Result:
- better development story
- using the latest & greatest
> use to NIO 2 (from master branch) and Swift 5

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
Compiling code is good so let's make it compile again with the latest
NIO APIs.
Modifications:
- made NIOTS use `_NIO1APIShims`
- clicked 'Fix All' a couple of times to adjust the API
Result:
Code compiles again
> port to latest NIO 2 APIs

- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
Some users may wish to use peer-to-peer networking with bonjour.
Modifications:
Expose peer-to-peer networking via a new channel option.
Result:
Users will be able to use peer-to-peer networking
> Support setting enablePeerToPeer.

- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
Some users may wish to use peer-to-peer networking with bonjour.
Modifications:
Expose peer-to-peer networking via a new channel option.
Result:
Users will be able to use peer-to-peer networking
(cherry picked from commit e9c1e41fd1a4e4c5908322c49d1db38795c13a12)
> Support setting enablePeerToPeer. (#22)

- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
Code should compile and have the latest NIO 2 API.
Modifications:
- rename `ctx` to `context`
- apply all fixits
Result:
compiles again
> update to latest NIO 2

- Package.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
Motivation:
Previously we would use the combination of DispatchQueue.asyncAfter and
a DispatchWorkItem for the connect timeout. If the connection succeeded
we would just cancel the DispatchWorkItem. Unfortunately that will still
keep everything that's captured in the DispatchWorkItem alive until the
deadline has come (because DispatchWorkItem is just a dumb wrapper over
a closure).
Modifications:
use a DispatchSource of type timer source instead.
Result:
- we won't keep the ELG/EL/Channel/... alive until at least the connect
timeout expires.
- fixes #28
> don't retain everything until connect timeout expires

- Package.swift
Motivation:
When entering convergence we incorrectly specified a branch dependency
for something that is actually a tag.
Modifications:
- Remove branch dependency, use from: instead.
Result:
Users can use this repo!
> Correctly avoid branch dependency.

- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
NIOTS will not work on Linux but we can at least make it not fail
compilation when compiled on Linux. That way consumers of the API can
depend on NIOTS but make sure they only use NIOTS when wrapped in a
`#if canImport(Network)` block.
Modification:
Guard everything by `#if canImport(Network)`
Result:
- This package will now build on Linux (without providing any useful code).
- fixes #21
> make NIOTS compile on Linux

- README.md
Motivation:
Stuff needs updating if you ship new major versions as it turns out.
Modification:
update readme to reflect the new, shiny NIO 2 world.
Result:
more accurate docs
> update readme for NIO2

- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
Motivation:
At least in some cases it's possible to have a local or remote address
that we cannot represent in a SocketAddress. In the face of that, we were
unnecessarily crashing. Crashes should probably be avoided there.
Modifications:
- Replace the crashes with throws.
Result:
Fewer crashes, more nils.
> Remove unnecessary traps.

- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
Motivation:
NWEndpoint is an open enum, so we should handle @unkown default in NIO
1. Also, some warnings need fixing.
Modifications:
- add `@unkown default` for NWEndpoint
- fix some warnings
Result:
happier users
> add @unknown default for NWEndpoint

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
While we fixed a bug in SwiftNIO about setting multiple options of the same type in
apple/swift-nio#597, we never brought a fix for that issue forward. We did aim to resolve
this in SwiftNIO 2.0 by providing ChannelOptions.Storage, but unfortunately we forgot to
make the initializer for that type public (see apple/swift-nio#988). While SwiftNIO core
has to get its ducks in a row, users of this library should still be able to set more than
one socket option, in my humble opinion.
Modifications:
- Ported over ChannelOptions.Storage until apple/swift-nio#988 is fixed.
- Transitioned our code to use it.
- Tested it works.
Result:
Users can set multiple channel options.
> Allow setting multiple options of the same type.

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
We never brought across the fix to apple/swift-nio#597 into swift-nio-transport-services. This
has caused some users a few hard-to-track-down surprises. We fixed this in the mainline by way
of #40, but users running the old codebase probably want this fix too.
Modifications:
- Side-ported the fix from apple/swift-nio#597.
- Back-ported the test from #40.
Result:
Users can set multiple socket options.
> Support setting multiple socket options.

- Package.swift
- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
- scripts/build_podspec.sh
Motivation:
It was not possible to import NIOTS into a project where
Network.framework was not supported by all deployment targets.
Modifications:
All NIOTS code, where applicable, was annotated with availability
attributes.
Result:
It is possible for application developers to import NIOTS on platforms
which do not support Network.framework without a compile time error.
> Annotate code with availability attributes

- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
The expectation is that server channels use Channel as their data type,
but the initial data type in NIOTSListenerChannel was actually
NWConnection. This is unnecessary and it makes it hard to interop
between NIOTS and NIO.
Modifications:
- Initialize the NIOTSConnectionChannel in the NIOTSListenerChannel
instead of in AcceptHandler.
- Added some missing @available annotations in the tests.
Result:
More consistency
Resolves #44.
> Pass Channels down pipeline not NWConnection

- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
Motivation:
With Network.framework becoming available on watchOS, you should now be
able to run your favourite NIO applications on watchOS 6!
Modifications:
Updated availability annotations to allow NIO TS.
Result:
More NIO on more watches
> Make NIO Transport Services available on watchOS 6

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
Networking software like SwiftNIO that always has explicit flushes
usually does not benefit from having TCP_NODELAY switched off. The
benefits of having it turned on are usually quite substantial and yet we
forced our users for the longest time to enable it manually.
Quite a bit of engineering time has been lost finding performance
problems and it turns out switching TCP_NODELAY on solves them
magically.
Netty has made the switch to TCP_NODELAY on by default, SwiftNIO should
follow. This patch is the equivalent of apple/swift-nio#1020.
Modifications:
Enable TCP_NODELAY by default.
Result:
If the user forgot to enable TCP_NODELAY, their software should now be
faster.
> Enable TCP_NODELAY by default.

- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
Motivation:
macOS Catalina brings a .url endpoint to Network.framework, which is
currently causing build warnings. We should tolerate it and silence
those warnings.
Modifications:
Do the right thing when we receive a .url endpoint.
Result:
No build warnings.
> Handle .url endpoint in switches over endpoint.

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
Motivation:
In NIO `ClientBootstrap` and `ServerBootstrap` are initialized with an
`EventLoopGroup`. Since `EventLoop` conforms to `EventLoopGroup` you can
initialize an bootstrap with an existing event loop. In NIO Transport
Services the bootstraps are initialized with a `NIOTSEventLoopGroup` and
as `NIOTSEventLoop` conforms to `EventLoop` and by extension
`EventLoopGroup` (but not `NIOTSEventLoopGroup`) it is not possible to
initialize a bootstrap with a pre-existing `NIOTSEventLoop`.
Modifications:
Change the bootstrap initializers to accept an `EventLoopGroup`.
Result:
NIO Transport Services bootstraps can be initialized with a
`NIOTSEventLoop`.
> Lower EventLoopGroup requirements for creating bootstraps

- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
Motivation:
`NWEndpoint` added a `.url` case for macOS 10.15 which commit afbbead added
support for. However, in doing so it also broke support for 10.14.
Modifications:
Handle `.url` in the `default` case and also remove `@unknown` from the
cases of the switch statements in NIOTSListenerChannel and SocketAddress
init.
Result:
Compiles on 10.14.
> Fix availability for NWEndpoint

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
Motivation:
When autoRead is on, the pipeline must observe the read calls in order
to be able to exert backpressure. Otherwise, autoRead is a
zero-backpressure mode, which isn't great.
Correctly call pipeline.read instead of self.read0 to avoid this.
Modifications:
- Updated NIOTSConnectionChannel to call pipeline.read().
Result:
Backpressure can be exerted.
> Correctly autoRead through the pipeline

- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
In Network.framework it is possible for a bind operation to take a while
to complete if it ends up waiting for appropriate network conditions. As
a result, unlike in the POSIX case, we need to give users the ability
to configure the maximum amount of time they'd be willing to wait for a
bind call to succeed.
Modifications:
- Add a bind timeout.
Result:
Users won't have to wait forever.
> Add a bind timeout.

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Motivation:
NIO on BSD Sockets had an issue where it wouldn't tolerate futures from
foreign EventLoops being returned from the channel initializers. NIOTS
should also have a test that tests this situation despite the fact that
it didn't have the same bug.
Modification:
- add a test case
- add more assertions
Result:
Better tests.
> Bootstrap: test that returning futures from foreign ELs are okay

- README.md
Add instructions on how to include NIO Transport Services using SPM
The best method now that Xcode has SPM support is to use the package, and not Cocoapods anymore
Update the readme
Everyone uses SPM now…
> Update Readme to recommend using Xcode package support

- Package.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
Motivation:
In NIO 2.9.0 we moved all first-party `ChannelOption` types into their
own namespace. That was a good idea, but NIOTS uses them too and so it
now encounters build warnings. Additionally, NIOTS defines its own
`ChannelOption`s, and so should namespace those as well.
Modifications:
- Updated the code to use the namespaced `ChannelOption` types.
- Namespaced our own.
Result:
More namespacing.
> Namespace ChannelOptions.

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
Motivation:
We can remove a couple of unnecessary flatMap { $0 } operations by way
of using flatSubmit, added in NIO 2.9.0.
Modifications:
- Replace flatMap { $0 } with flatSubmit().
Result:
Remove some code noise.
> Take advantage of flatSubmit.

- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
Motivation:
Sadly the previous NIO warnings patch failed to notice that the tests
had a bunch of errors, despite the fact that those tests were
(repeatedly) run.
Modifications:
Directly apply the fixits.
Result:
Fewer warnings
> Fixup some warnings in the tests.

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
Motivation:
We deprecated Atomic because we made a new, better one. We should use
it.
Modifications:
Replaced all use of Atomic with NIOAtomic.
Result:
Better performance, fewer compiler warnings.
> Adopt NIOAtomic

- Sources/NIOTransportServices/NIOTSBootstraps.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Motivation:
Today, we just expect the ELGs passed to the bootstraps to be the
correct ones, if not, we crash.
Modifications:
Offer an alternative validatingGroup: init that just returns nil
if the ELGs are of the wrong types.
Result:
Easier to work with multi-stack systems for example when the user might
pass an ELG for either NIO on Sockets or NIO on Network.framework.
This is the NIOTS companion for https://github.com/apple/swift-nio/pull/1464
> bootstraps: offer ELG validation

- Sources/NIOTransportServices/NIOTSBootstraps.swift
Add canImport(Network) to NIOTSBootstraps.swift
Still needs to compile in Linux
> Add canImport(Network) to NIOTSBootstraps.swift

- Tests/NIOTransportServicesTests/NIOFilterEmptyWritesHandlerTests.swift
The tests should also compile (and do nothing) on Linux.
> add missing canImport(Network) to tests

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
ChannelOptions.Storage was duplicated from swift-nio - undo this.
The code was an exact duplicate of that from Swift-NIO with a comment to undo this.  The conditions for undoing the clone have been true for over a year.
Delete ChannelOptionsStorage.  Where used replace with ChannelOptions.Storage from nio.
Less total code.
> Deduplicate ChannelOptions.Storage with swift-nio

- Sources/NIOTransportServices/NIOTSEventLoop.swift
Removed the `message` parameters and the now meaningless explanatory comments, added the missing `@inlineable`s to match the other PR.
> Update according to additional feedback on apple/swift-nio#1508

- README.md
Motivation:
We have a weird availability model for NIOTS since we can build it even
if Network.framework isn't available: we don't document this anywhere.
Modifications:
Explain supported platform model in the README.
Result:
Better documentation.
> Add supporter platforms to README

- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
Motivation:
It's not obvious what happens when `childChannelInitializer` returns a
failed future. See https://github.com/apple/swift-nio/pull/1516
Modifications:
Add a note to the `childChannelInitializer` documentation.
Result:
Better docs.
> Add a note about failing child channel initializers

- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Tests/NIOTransportServicesTests/NIOTSChannelOptionsTests.swift
This is a draft for implementing https://github.com/apple/swift-nio-transport-services/issues/88.
It adds new channel options in `NIOTSChannelOptions` and handles these in `getOption` of `NIOTSConnectionChannel`.
The collection of a `NWConnection.DataTransferReport` is not quite right in this implementation. I couldn't find a way to do it, so that part must probably be refactored. I posted what I have anyway, for sake of learning and discussion.
> New channel options exposing properties of underlying NWConnection

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Motivation:
On Apple's devices it is considered a best practice to wait for network
connectivity in cases when a connection request cannot immediately be
satisfied, rather than erroring out. This reflects the dynamic and fluid
network environment on Apple devices, with their many network interfaces
and complex interactions between radios, VPNs, and network devices.
While NIOTS supports this model of interaction (and indeed uses it out
of the box), and supports configuring it (by setting
`NIOTSChannelOptions.waitForActivity`), a key pillar is missing:
observability. Right now we don't actually _tell_ the user when we're
waiting for connectivity. This makes it difficult to act on this
information.
Modifications:
- Added a user event, `NIOTSNetworkEvents.WaitingForConnectivity` that
is fired …
> Add user event fired when waiting for connectivity.

- scripts/build_podspec.sh
Motivation:
The build_podspec.sh script generates a podspec which requires exact
versions of its dependencies. This very quickly turns into unresolvable
dependency graphs.
Modifications:
NIO version passed to script must be in the format MAJOR.MINOR
Podspec dependencies are now '>= MAJOR.MINOR', '< MAJOR+1'
Result:
Looser version requirements for podspecs
> Update build_podspec.sh to not use exact dependency versions

- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
Motivation:
only works if done when _calling_ a function, not when defining one :|.
- https://github.com/apple/swift/pull/32445
- https://bugs.swift.org/browse/SR-12936
- https://bugs.swift.org/browse/SR-12934
- https://bugs.swift.org/browse/SR-13041
Modifications:
Silence #file to #filePath differently.
Result:
Hopefully at some point we get this working.
> silence #file to #filePath differently

- Sources/NIOTransportServices/NIOTSChannelOptions.swift
Motivation:
In a patch where we added some metadata options, we accidentally set the
availability wrong. This is a compile-time error, so we broke watchOS
compilation.
Modifications:
Update the availability of some types on watchOS.
Result:
Users can build on watchOS again.
> Update watchOS availability.

- Package.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Directly support the allowLocalEndpointReuse channel option including mapping from shorthand options.  Also add shorthand options for client.
The NetworkFramework directly supports the concept of allowLocalEndPointReuse.  Currently to get through the nio system, this is mapped to the SO_REUSEADDR option.  
Now there is a shorthand option for this, it is sad to map from allowLocalEndPointReuse to SO_REUSEADDR and back again.
Add a new NIOTS channel option for this setting.
Set the underlying based on any of new setting, reuseAddr or reusePort.
Add a override to interpret the shorthand option directly into the new option.
Add shorthand options for client with tests of equivalence to long options.
Behaviour is identical but we can feel happier that the option mapping is less confusing.
> Directly support the allowLocalEndpointReuse channel option

- docker/Dockerfile
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.yaml
Motivation:
It's important that transport-services compiles and does nothing
on linux so it can be used in builds which just do the right thing
on all platforms.
Modifications:
Add basic docker-compose files based on those from swift-nio
Result:
It's possible to run docker on this repo to run the tests.
> Add docker config for swift-nio-transport-services

- docker/docker-compose.1804.50.yaml
Motivation:
Docker shell was incorrectly using the swift-nio docker image
rather than the swift-nio-transport-services one.
Modifications:
Change docker compose file to use the correct image.
Result:
Correct image will be used for docker shell.
> Fix docker shell to use correct image.

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Motivation:
Network.framework will crash when we attempt to connect to the host
string "". That's not ideal, so we should detect that case and avoid it.
Modifications:
- Add code to detect the empty host string.
Result:
No crashes when accidentally connecting to "".
> Avoid crashing when connecting to empty host.

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
Motivation:
xcodebuild complains during Cocapods validation (which fails as a
result) about a redundant availability check. It's redundant because for
watchOS the availability guard on the outer scope has the same
conditions (for other platforms the conditions are tighter in the
inner scope). We never hit this before because we only recently added
watchOS to the supported platforms for Cocapods.
Modifications:
- Remove a redundant availability check
Result:
- Cocoapods can validate without error
> Remove a redundant availability check

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Motivation:
We shouldn't crash if the user gives us a bad port.
Modifications:
- Check the ports are in-band before we move on.
Result:
We won't crash.
> Tolerate out-of-band ports.

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Motivation:
NIO 2.27.0 added optional support for synchronous channel options.
NIOTSListenerChannel and NIOTSConnectionChannel should support this.
Modifications:
- Add synchronous options for NIOTSConnectionChannel and
NIOTSListenerChannel
- Avoid an allocation in 'getOption' for each channel if the caller is
already on the right event loop by using 'makeSucceededFuture'
- Remove a no longer used internal function and an already dead private
helper
Result:
- Support for sync options and fewer allocations
> Add support for syncOptions to NIOTSListenerChannel and NIOTSConnectionChannel

- Package.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
Motivation:
`removeHandlers(channel:)` was deprecated in NIO 2.32.0.
Modifications:
- Raise minimum required NIO version to 2.32.0
- Use `removeHandlers(pipeline:)`
Result:
We don't use deprecated API.
> Use non-deprecated API for removing handlers

- Package.swift
- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
- Sources/NIOTransportServices/NIOFilterEmptyWritesHandler.swift
- Sources/NIOTransportServices/NIOTSBootstraps.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSErrors.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
- Sources/NIOTransportServices/SocketAddress+NWEndpoint.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Sources/NIOTransportServices/TCPOptions+SocketChannelOption.swift
- Tests/NIOTransportServicesTests/NIOFilterEmptyWritesHandlerTests.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
- Tests/NIOTransportServicesTests/NIOTSChannelOptionsTests.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
- scripts/soundness.sh
Motivation:
With NIO 2.32.0 we broke the core NIO module up into modules that split
apart the POSIX layer and the core abstractions. As a result, this
package no longer needs to express a hard dependency on the POSIX layer.
Modifications:
- Rewrote imports of NIO to NIOCore.
- Added NIOEmbedded imports where necessary in tests.
- Note that the main package still _depends_ on NIO, which is necessary
for backwards-compatibility reasons. This dependency is unused.
Result:
No need to use NIOPosix.
> Clean up imports and dependencies.

- Sources/NIOTransportServices/NIOTSEventLoop.swift
Motivation:
When a task is scheduled using a `DispatchTimerSource` on a `NIOTSEventLoop`
the source is retain via a callback on the promise associated with the
scheduled task. This stops the source from deinit'd before the task is
run. However, the callback being added is an implementation details of
`Scheduled` and the retain cycle is incidental.
If that detail chnaged (such as in
https://github.com/apple/swift-nio/pull/2011) then tasks may not run and
the promise could be leaked.
Modifications:
- Explicitly add a retain cycle between the future and the timer source
which is broken by the promise being completed and callbacks run.
Result:
The timer source is kept alive until the event fires.
> Explicitly retain timer source when scheduling tasks

- docker/docker-compose.2004.55.yaml
- docker/docker-compose.2004.56.yaml
The 5.6 nightly images are available, let's use them.
@tomerd Can you add a 5.6 builder here?
> Add 5.6 nightly CI

- scripts/build_podspec.sh
Motivation:
To workaround https://github.com/apple/swift-nio/issues/2073 we must
list all transitive dependencies when building podspecs.
Modifications:
- Include transitive dependencies in the build_podspec script
- The list of dependencies was generated using
the `list_transitive_dependencies.py` from the NIO repo.
Result:
Podspec generation script includes transitive dependencies.
> Update podspec script

- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
_[One line description of your change]_
Change NIOTSNetworkEvent initializers visibility to public level.
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
Solves issue #147. Public initializers allow to extend unit test of async-http-client. For more details, see [async-http-client \#589](https://github.com/swift-server/async-http-client/issues/589) 
_[Describe the modifications you've done.]_
Add public initializers for all NIOTSNetworkEvents.
_[After your change, what will change.]_
NIOTSNetworkEvent initializers will be available across different packages.
> change NIOTSNetworkEvent initializers visibility to public level

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Motivation:
When we're waiting for connectivity, the user might tell us that they
aren't interested in waiting. In that case we take advantage of the
signal and close early.
However, the code as-written had a bug: we didn't care whether the user
told us they _didn't_ want to wait, or they _did_: we just closed
because they had an opinion! That's no good! We should only close if
they don't want to wait.
Modifications:
- Only close if the user doesn't want to wait.
- Add tests
Result:
We won't close if users don't want us to.
> Don't close when waiting unless we were asked to.

- README.md
Motivation:
We no longer support Cocoapods and `swift package generate-xcodeproj` is
deprecated, so we shouldn't advertise their usage in the README.
Modifications:
Remove Cocoapods and `swift package generate-xcodeproj` sections from
the README.
Result:
More up-to-date README
> Remove outdated docs from README

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
`NIOAtomics` was deprecated in https://github.com/apple/swift-nio/pull/2204 in favor of `swift-atomics` https://github.com/apple/swift-atomics
> Use `swift-atomics` instead of `NIOAtomics`

- Package.swift
- Sources/NIOTransportServices/NIOFilterEmptyWritesHandler.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
Bumps `swift-nio` to `2.41.1` to have access to `NIOPreconcurrencySendable`.
`NIOTSMetadataOption` should probably be marked non-Sendable because it contains a reference type `NWProtocolDefinition` (and the Value of type `NWProtocolMetadata` is also a reference type). Network.framework has not adopted Sendable so it is hard to say if it is Sendable or not.  However, `NIOTSMetadataOption` conforms to `ChannelOption` which inherits from `NIOPreconcurrencySendable` and therefore must be `Sendable`. We will need to decided what we do with that type but that can be done separately.
> Adopt `Sendable`

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedChannel.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
NIO Transport Services is not capable of launching services with existing NWConnection or NWListener objects. Being able to get an existing NWConnection through a connection bootstrap and into a channel is a useful capability for advanced use cases.
Modifications:
* Added an option to bootstrap with existing NWListener and NWConnection
* Completed promise connection earlier within NIOTSChannels when AlreadyConfigured is called
* Added test with new NWConnection and NWListener to register Channels
Result:
Able to create and register a channel using an existing NWListener and NWConnection
> Launching Services with existing NWConnection or NWListener objects

- Package.swift
- Package@swift-5.4.swift
- Package@swift-5.5.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Motivation:
Lock has been deprecated in favour of NIOLock. Warnings aren't great.
Modifications:
- Replace Lock with NIOLock
- Update the minimum required NIO version to 2.42.0.
Result:
Everything builds cleanly
> Replace Lock with NIOLock

- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
I was wrong: https://github.com/apple/swift-nio-transport-services/pull/161#discussion_r994483143
Network.framework has not adopted `Sendable` yet. We therefore need to import it with `@preconcurrency`. `@preconcurrency` is only available in Swift 5.6.
> Fix Swift 5.5

- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
- Tests/NIOTransportServicesTests/NIOTSChannelMetadataTests.swift
We want to log the TLS version in gRPC. To get at the TLS version if `NIOTS` is in use, we need to retrieve the `NWProtocolTLS.Metadata` from a  `NWConnection`.
- add `Channel.getMetadata(definition:)` and `Channel.getMetadataSync(definition:)`
Users outside of this library can now access metadata of an `NWConnection`.
> Allow retrieval of metadata from `NWConnection`

- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
Motivation:
#fileID introduced in Swift 5.3, so no longer need to use #file anywhere                                  
Modifications:
Changed #file to #filePath because of XCT Assertions
> Use #fileID/#filePath instead of #file

- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSChannelOptionsTests.swift
Motivation
As we've rolled out support for multicast on Linux, it makes sense to add equivalent configuration for swift-nio-transport-services. The two features aren't one-to-one, as Network.framework has substantially more capability than the Linux functionality.
Modifications
- Expose a multipathServiceType channel option
- Add a test to confirm we use it properly
Result
Multicast service types are available.
> Expose multicast service type

- Sources/NIOTransportServices/Docs.docc/index.md
Motivation:
We try to support building our docs on Linux too, but that means we can't explicitly reference any symbols from `index.md`.
Modifications:
Enable CI-ing docs.
Result:
Docs will render on Linux too.
> Drop Topics section

- Package.swift
- Sources/NIOTransportServices/NIOTSNetworkEvents.swift
`swift-nio` has deprecated `NIOPreconcurrencySendable` in `2.51.0`. Removing the protocol conformance would be an API breaking change. Keeping the conformance is low cost and not worth the risk.
- replace `NIOPreconcurrencySendable` with underscore version `_NIOPreconcurrencySendable`
We compile again with the latest `swift-nio` release without warnings
> Use underscore version of `NIOPreconcurrencySendable` to silence warning

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
We want to support async bootstrapping with all our bootstraps.
This PR adds support for the `NIOTSListenerBootstrap` and `NIOTSConnectionBootstrap`. It also adds the three variants of methods to it (abstract output, `NIOAsyncChannel` based and protocol negotiation based)
We now support asynchronous interaction with the `NIOTSListenerBootstrap` and `NIOTSConnectionBootstrap`
> Async methods for `NIOTSListenerBootstrap` and `NIOTSConnectionBootstrap`

- Sources/NIOTransportServices/AcceptHandler.swift
- Sources/NIOTransportServices/NIOFilterEmptyWritesHandler.swift
- Sources/NIOTransportServices/NIOTSBootstraps.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedListenerChannel.swift
- Sources/NIOTransportServices/UDPOptions+SocketChannelOption.swift
- Tests/NIOTransportServicesTests/NIOFilterEmptyWritesHandlerTests.swift
- Tests/NIOTransportServicesTests/NIOTSChannelOptionsTests.swift
Extract the NWListener code into `StateManagedListenerChannel`
When implementing #68, a lot of code ended up being identical between TCP and UDP. Like #174, this PR paves the way to adding UDP, with very little overhead code. It moves the code that is used to represent NWListener as a Channel into its own protocol, that can then be applied to both TCP and UDP implementations.
- Added `StateManagedListenerChannel` that has all the logic for handling a NWConnection as a NIO.Channel.
- Made the AcceptHandler generic for use with both TCP and UDP
This makes implementing UDP much simpler, and without redundant code.
This PR works off #174 , and should therefore be viewed as a diff based on #174 to get a clean picture.
> State Managed Listeners

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
We introduced a new configuration struct for `NIOAsyncChannel` to make handling and configuring it easier.
This PR adopts the new APIs.
Less boilerplate in our bootstrap methods
> Adopt the `NIOAsyncChannel.Configuration`

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
We introduced some breaking SPI(AsyncChannel) changes in NIO that we have to adopt here.
This PR adopts the latest `NIOProtocolNegotiationResult` APIs. Additionally, it also drops all bind/connect methods on the bootstraps that are specific to protocol negotiation or `NIOAsyncChannel`.
Green CI on `main` and alignment between `NIOPosix` and `NIOTS.
> Adopt latest SPI(AsyncChannel) changes

- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
After my recent PR we failed to compile on 5.6 since the compiler isn't capable to infer the return type of one of the closures.
This PR adds the closure's return type explicitly.
Compiling on 5.6 again
> Fix 5.6 compiler error

- Package.swift
- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
We had some breaking changes in the NIO AsyncChannel SPI which we have to adapt here.
This PR updates to the latest AsyncChannel SPI
No more warnings and errors when building.
> Adopt latest AsyncChannel SPI changes

- Package.swift
- Sources/NIOTransportServices/NIOTSEventLoop.swift
- Sources/NIOTransportServices/NIOTSEventLoopGroup.swift
- Sources/NIOTransportServices/NIOTSSingletons.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSSingletonTests.swift
(companion PR to https://github.com/apple/swift-nio/pull/2471)
SwiftNIO allows and encourages to precisely manage all operating system resources like file descriptors & threads. That is a very important property of the system but in many places -- especially single Swift Concurrency arrived -- many simpler SwiftNIO programs only require a single, globally shared EventLoopGroup. Often even with just one thread.
Long story short: Many, probably most users would happily trade precise control over the threads for not having to pass around `EventLoopGroup`s. Today, many of those users resort to creating (and often leaking) threads because it's simpler. Adding singletons type which _lazily_ provide a singleton `EventLoopGroup` and an `NIOThreadPool` is IMHO a much better answer.
- Add …
> NIOSingletonsTransportServices: Use NIOTS in easy mode

- Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
Motivation:
The datagram tests use a handler which sets its event loop in `channelRegistered`. A function on the handler is called which relies on the EL being set. However, this can race: the function can be called before `channelRegistered` is called.
Modifications:
- set the EL in `handlerAdded`
Result:
Fewer crashes
> Avoid race in datagram tests

- Sources/NIOTransportServices/StateManagedListenerChannel.swift
- Sources/NIOTransportServices/StateManagedNWConnectionChannel.swift
This PR addresses issue #133.
There was a typo when setting the allowLocalEndpointReuse channel option, where it was cast to NIOTSEnablePeerToPeerOption.Value instead of NIOTSAllowLocalEndpointReuse.Value. Both of these types are Bools, so this wouldn't cause any actual issues, this change is to more to keep the code consistent, and reduce confusion for future contributors or others reading the code base.
This commit casts the allowLocalEndpointReuse property in StateManagedListenerChannel and StateManagedNWConnectionChannel.
The typo is fixed after this change.
> Fix a typo when casting the allowLocalEndpointReuse channel option value

- Package.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSAsyncBootstrapTests.swift
We just merged the removal of the `AsyncChannel` SPI in NIO and can now add back the new APIs in transport services as well.
This PR brings back the previous SPI and promotes it to API.
New typed async bootstraps API for `NIOTransportServices`.
> Add new typed async bootstrap APIs back and drop SPI

- Sources/NIOTSHTTPClient/main.swift
- Sources/NIOTSHTTPServer/main.swift
We missed a few availability guards in our tests which caused errors when compiling for older Darwin platforms.
This PR adds the missing guards.
We should build on all supported platforms again
> Fix availability guards and compiler warnings

- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSEndToEndTests.swift
- Tests/NIOTransportServicesTests/NIOTSEventLoopTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionTests.swift
- Tests/NIOTransportServicesTests/NIOTSSocketOptionsOnChannelTests.swift
This project doesn't currently build for watchOS because the availability guards are missing for watchOS.
Extend the availability guards to include watchOS.
Can build for watchOS.
> Fix build on watchOS

- Sources/NIOTransportServices/Datagram/NIOTSDatagramBootstrap.swift
- Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
- Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
Looks like when we previously added syncOptions support to our channels, we had a few issues. The listeners had code added, but the code never worked. This is because the code was defined in subclasses, but the protocol conformance comes from the parent class, and that parent class did not have a customized protocol witness.
The datagram channel was also entirely missing its support.
Modifications:
- Added the missing unit tests for sync options.
- Added syncOptions to StateManagedListenerChannel base class.
- Added overrides to the listener subclasses.
- Added syncOptions to datagram channel
Result:
Sync options actually work across the board.
> Fix the syncOptions on most channels

- Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
- Sources/NIOTransportServices/NIOTSChannelOptions.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/StateManagedListenerChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSListenerChannelTests.swift
Motivation:
In some cases users may want to access APIs we haven't exposed in NIOTransportServices. We should have a fallback that allows users to do this.
Modifications:
- Add ChannelOptions for getting NWConnection and NWListener.
Result:
Users have an escape hatch
> Add ChannelOptions to extract base types.

- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
Allow different devices to leverage the capabilities of Mutipath TCP (MPTCP) to enhance the network reliability. Thanks to MPTCP, a connection can for example automatically migrate to another interface if it deteriorates on the first one. This can be especially interesting on MacOS X and iOS, where devices may frequently benefit from multiple interfaces (ethernet + Wi-Fi for Macs and Wi-fi + cellular for iOS). Allowing developers to enable MPTCP on their connections seems thus like a fine addition to this library.
Added a function "withMultipath" on NIOTSConnectionBootstrap, that allow to configure the type of service used for MPTCP (defaults to disabled). This value will be stored in a field, and then propagated to the underlying channel when the connect method will be called. Also …
> Add configuration of multipathServiceType in NIOTSConnectionBootstrap

- Package.swift
- scripts/check-docs.sh
Motivation:
Swift Package Index builds our docs for us and will automatically insert the dependency.
Modifications:
- Remove the docc-plugin dependency
Result:
Fewer dependencies
> We no longer require the docc plugin

- Package.swift
Don't depend on NIOFoundationCompat in NIOTransportServices on Linux
I'm trying to build a small utility tool based on mqtt-nio which depends on NIOTransportServices. I noticed that NIOTransportServices depends on NIOFoundationCompat on all platforms but only imports it where the Network framework is available. Removing this dependency on non-Apple platforms allows us to not import Foundations, significantly reducing the size of the build product when using the Swift Static Linux SDK.
This PR and a similar one to mqtt-nio.
Hello world docker image depending on mqtt-nio went from 169MB to 85MB.
> Don't depend on NIOFoundationCompat in NIOTransportServices on Linux

- Package.swift
This reverts commit 40ffcdef465d0870113b531b08454fe1712c01de in PR #209.
Unfortunately, Swift's behaviour around imports tends to be somewhat "leaky". In this case, the leak is that the dependency on the Package.swift allows downstream projects to import `NIOFoundationCompat` without needing to actually specify the package dependency. This has affected Hummingbird, which we noticed on our internal integration testing functionality:
```
hummingbird/Sources/Hummingbird/Codable/JSON/JSONCoding.swift:18:8: error: no such module 'NIOFoundationCompat'
import NIOFoundationCompat
^
```
cc @Joannis @adam-fowler for the Hummingbird report.
Unfortunately, we can't make this change until we're willing to use a semver major to achieve it. There may be some argument for doing that now, as the semver …
> Revert "Don't depend on NIOFoundationCompat in NIOTransportServices on Linux (#209)"

- .github/workflows/main.yml
Remove the integration tests workflow from the main and scheduled jobs.
There are no integration tests in this repository.
(see https://github.com/apple/swift-nio-transport-services/actions/runs/11833082880)
Remove the integration tests workflow from the main and scheduled jobs.
No more scheduled run failures.
> Remove integration tests workflow

- Sources/NIOTransportServices/NIOTSSingletons.swift
- Sources/NIOTransportServices/StateManagedNWConnectionChannel.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
Motivation:
Dispatch wasn't imported in `NIOTSSingletons.swift` where `.default` was used for the default QoS. This causes some build issues.
Modifications:
- Add missing Dispatch import
Result:
Fewer build issues
> Add missing Dispatch import

- Sources/NIOTransportServices/Datagram/NIOTSDatagramBootstrap.swift
- Sources/NIOTransportServices/Datagram/NIOTSDatagramChannel.swift
- Sources/NIOTransportServices/Datagram/NIOTSDatagramListener.swift
- Sources/NIOTransportServices/Datagram/NIOTSDatagramListenerChannel.swift
- Sources/NIOTransportServices/NIOTSConnectionBootstrap.swift
- Sources/NIOTransportServices/NIOTSConnectionChannel.swift
- Sources/NIOTransportServices/NIOTSListenerBootstrap.swift
- Sources/NIOTransportServices/NIOTSListenerChannel.swift
- Sources/NIOTransportServices/StateManagedListenerChannel.swift
- Sources/NIOTransportServices/StateManagedNWConnectionChannel.swift
- Tests/NIOTransportServicesTests/NIOTSBootstrapTests.swift
- Tests/NIOTransportServicesTests/NIOTSChannelMetadataTests.swift
- Tests/NIOTransportServicesTests/NIOTSConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSDatagramConnectionChannelTests.swift
- Tests/NIOTransportServicesTests/NIOTSTestUtilities.swift
Allow users to provide a closure taking an `NWParameters` to customise them before they're used to create `NWConnection`s.
`NWParameters` are currently created using the provided TLS and UDP options, and then passed over to new `NWConnection`s. However, there are more ways in which `NWParameters` can be customised, so this new API provides a way for users to do this.
Introduce new `configureNWParameters` methods to the existing bootstraps to allow configuring a closure for customising `NWParameters`.
Users can now customise the `NWParameters` used to create new `NWConnection`s.
> Add `NWParameters` configurator to bootstraps

- Sources/NIOTransportServices/NIOTSEventLoop.swift
Every EventLoop can also be a SerialExecutor. Let's opt into the default NIO fast-path implementation.
SemVer patch as NIOTSEventLoop isn't public API.
> `NIOTSEventLoop` conforms to `NIOSerialEventLoopExecutor`
